### ISSUE TITLE
New MyInfo V3 API

### ISSUE THREAD

**Issue by sbycrosz** [opengovsg/myinfo-gov-client#3]
Hey! Big thanks for the library!

Correct me if I'm wrong, but according to this [documentation](https://www.ndi-api.gov.sg/library/trusted-data/myinfo/introduction), the 
V2 API implemented in this library will be deprecated 
Any chance this will be updated to the new V3 API? :)

Cheers, 
Sam

**Comment by LoneRifle** [comment]
Hello @sbycrosz, and thanks for pointing this out! At this point in time, it might make sense to make use of [singpass-myinfo-oidc-helper](https://github.com/GovTechSG/singpass-myinfo-oidc-helper), maintained by our GovTech colleagues in Government Digital Services (GDS). Afaict, they support v3
